-- Custom validation constraints and triggers for Svitlo
-- This migration is hand-written (not auto-generated by drizzle-kit)

-- ══════════════════════════════════════════════════════════════════════════════
-- CHECK CONSTRAINTS
-- ══════════════════════════════════════════════════════════════════════════════

-- ── organizations ────────────────────────────────────────────────────────────

ALTER TABLE "organizations" ADD CONSTRAINT "chk_organizations_name_not_empty"
  CHECK (length(trim("name")) > 0);

-- ── generators ───────────────────────────────────────────────────────────────

ALTER TABLE "generators" ADD CONSTRAINT "chk_generators_name_not_empty"
  CHECK (length(trim("name")) > 0);

ALTER TABLE "generators" ADD CONSTRAINT "chk_generators_type_not_empty"
  CHECK (length(trim("generator_type")) > 0);

ALTER TABLE "generators" ADD CONSTRAINT "chk_generators_max_run_hours_positive"
  CHECK ("max_consecutive_run_hours" > 0);

ALTER TABLE "generators" ADD CONSTRAINT "chk_generators_rest_hours_positive"
  CHECK ("required_rest_hours" > 0);

ALTER TABLE "generators" ADD CONSTRAINT "chk_generators_warning_pct_range"
  CHECK ("run_warning_threshold_pct" BETWEEN 1 AND 100);

-- ── maintenance_templates ────────────────────────────────────────────────────

ALTER TABLE "maintenance_templates" ADD CONSTRAINT "chk_templates_task_name_not_empty"
  CHECK (length(trim("task_name")) > 0);

ALTER TABLE "maintenance_templates" ADD CONSTRAINT "chk_templates_hours_interval_positive"
  CHECK ("trigger_hours_interval" IS NULL OR "trigger_hours_interval" > 0);

ALTER TABLE "maintenance_templates" ADD CONSTRAINT "chk_templates_calendar_days_positive"
  CHECK ("trigger_calendar_days" IS NULL OR "trigger_calendar_days" > 0);

-- ── invitations ──────────────────────────────────────────────────────────────

ALTER TABLE "invitations" ADD CONSTRAINT "chk_invitations_email_not_empty"
  CHECK (length(trim("invitee_email")) > 0);

-- ══════════════════════════════════════════════════════════════════════════════
-- TRIGGERS
-- ══════════════════════════════════════════════════════════════════════════════

-- ── 1. Maintenance template: enforce required fields based on trigger_type ──

CREATE OR REPLACE FUNCTION validate_maintenance_template_trigger_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.trigger_type IN ('hours', 'whichever_first')
     AND NEW.trigger_hours_interval IS NULL THEN
    RAISE EXCEPTION 'trigger_hours_interval is required when trigger_type is %',
      NEW.trigger_type;
  END IF;

  IF NEW.trigger_type IN ('calendar', 'whichever_first')
     AND NEW.trigger_calendar_days IS NULL THEN
    RAISE EXCEPTION 'trigger_calendar_days is required when trigger_type is %',
      NEW.trigger_type;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_maintenance_template_fields
  BEFORE INSERT OR UPDATE ON "maintenance_templates"
  FOR EACH ROW
  EXECUTE FUNCTION validate_maintenance_template_trigger_fields();

-- ── 2. Organizations: admin_user_id is immutable (MVP) ──────────────────────

CREATE OR REPLACE FUNCTION validate_org_admin_immutable()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.admin_user_id IS DISTINCT FROM OLD.admin_user_id THEN
    RAISE EXCEPTION 'admin_user_id cannot be changed';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_org_admin_immutable
  BEFORE UPDATE ON "organizations"
  FOR EACH ROW
  EXECUTE FUNCTION validate_org_admin_immutable();
