/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DashboardOrganizationIdRouteRouteImport } from './routes/dashboard/$organizationId/route'
import { Route as DashboardOrganizationIdIndexRouteImport } from './routes/dashboard/$organizationId/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardOrganizationIdGeneratorsRouteRouteImport } from './routes/dashboard/$organizationId/generators/route'
import { Route as DashboardOrganizationIdSettingsIndexRouteImport } from './routes/dashboard/$organizationId/settings/index'
import { Route as DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteImport } from './routes/dashboard/$organizationId/generators/$generatorId/route'
import { Route as DashboardOrganizationIdGeneratorsGeneratorIdIndexRouteImport } from './routes/dashboard/$organizationId/generators/$generatorId/index'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute
} as any)
const DashboardOrganizationIdRouteRoute =
  DashboardOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardRouteRoute
  } as any)
const DashboardOrganizationIdIndexRoute =
  DashboardOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationIdRouteRoute
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport
} as any)
const DashboardOrganizationIdGeneratorsRouteRoute =
  DashboardOrganizationIdGeneratorsRouteRouteImport.update({
    id: '/generators',
    path: '/generators',
    getParentRoute: () => DashboardOrganizationIdRouteRoute
  } as any)
const DashboardOrganizationIdSettingsIndexRoute =
  DashboardOrganizationIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardOrganizationIdRouteRoute
  } as any)
const DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute =
  DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteImport.update({
    id: '/$generatorId',
    path: '/$generatorId',
    getParentRoute: () => DashboardOrganizationIdGeneratorsRouteRoute
  } as any)
const DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute =
  DashboardOrganizationIdGeneratorsGeneratorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/dashboard/$organizationId': typeof DashboardOrganizationIdRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$organizationId/generators': typeof DashboardOrganizationIdGeneratorsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/$organizationId/': typeof DashboardOrganizationIdIndexRoute
  '/dashboard/$organizationId/generators/$generatorId': typeof DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteWithChildren
  '/dashboard/$organizationId/settings/': typeof DashboardOrganizationIdSettingsIndexRoute
  '/dashboard/$organizationId/generators/$generatorId/': typeof DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$organizationId/generators': typeof DashboardOrganizationIdGeneratorsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/$organizationId': typeof DashboardOrganizationIdIndexRoute
  '/dashboard/$organizationId/settings': typeof DashboardOrganizationIdSettingsIndexRoute
  '/dashboard/$organizationId/generators/$generatorId': typeof DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard/$organizationId': typeof DashboardOrganizationIdRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$organizationId/generators': typeof DashboardOrganizationIdGeneratorsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/$organizationId/': typeof DashboardOrganizationIdIndexRoute
  '/dashboard/$organizationId/generators/$generatorId': typeof DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteWithChildren
  '/dashboard/$organizationId/settings/': typeof DashboardOrganizationIdSettingsIndexRoute
  '/dashboard/$organizationId/generators/$generatorId/': typeof DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/$organizationId'
    | '/sign-in'
    | '/api/$'
    | '/dashboard/'
    | '/dashboard/$organizationId/generators'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/$organizationId/'
    | '/dashboard/$organizationId/generators/$generatorId'
    | '/dashboard/$organizationId/settings/'
    | '/dashboard/$organizationId/generators/$generatorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/$'
    | '/dashboard'
    | '/dashboard/$organizationId/generators'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/$organizationId'
    | '/dashboard/$organizationId/settings'
    | '/dashboard/$organizationId/generators/$generatorId'
  id:
    | '__root__'
    | '/dashboard'
    | '/_auth'
    | '/_marketing'
    | '/dashboard/$organizationId'
    | '/_auth/sign-in'
    | '/api/$'
    | '/_marketing/'
    | '/dashboard/'
    | '/dashboard/$organizationId/generators'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/$organizationId/'
    | '/dashboard/$organizationId/generators/$generatorId'
    | '/dashboard/$organizationId/settings/'
    | '/dashboard/$organizationId/generators/$generatorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/$organizationId': {
      id: '/dashboard/$organizationId'
      path: '/$organizationId'
      fullPath: '/dashboard/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$organizationId/': {
      id: '/dashboard/$organizationId/'
      path: '/'
      fullPath: '/dashboard/$organizationId/'
      preLoaderRoute: typeof DashboardOrganizationIdIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$organizationId/generators': {
      id: '/dashboard/$organizationId/generators'
      path: '/generators'
      fullPath: '/dashboard/$organizationId/generators'
      preLoaderRoute: typeof DashboardOrganizationIdGeneratorsRouteRouteImport
      parentRoute: typeof DashboardOrganizationIdRouteRoute
    }
    '/dashboard/$organizationId/settings/': {
      id: '/dashboard/$organizationId/settings/'
      path: '/settings'
      fullPath: '/dashboard/$organizationId/settings/'
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdRouteRoute
    }
    '/dashboard/$organizationId/generators/$generatorId': {
      id: '/dashboard/$organizationId/generators/$generatorId'
      path: '/$generatorId'
      fullPath: '/dashboard/$organizationId/generators/$generatorId'
      preLoaderRoute: typeof DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteImport
      parentRoute: typeof DashboardOrganizationIdGeneratorsRouteRoute
    }
    '/dashboard/$organizationId/generators/$generatorId/': {
      id: '/dashboard/$organizationId/generators/$generatorId/'
      path: '/'
      fullPath: '/dashboard/$organizationId/generators/$generatorId/'
      preLoaderRoute: typeof DashboardOrganizationIdGeneratorsGeneratorIdIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute
    }
  }
}

interface DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteChildren {
  DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute: typeof DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute
}

const DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteChildren: DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteChildren =
  {
    DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute:
      DashboardOrganizationIdGeneratorsGeneratorIdIndexRoute
  }

const DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteWithChildren =
  DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute._addFileChildren(
    DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteChildren
  )

interface DashboardOrganizationIdGeneratorsRouteRouteChildren {
  DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute: typeof DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteWithChildren
}

const DashboardOrganizationIdGeneratorsRouteRouteChildren: DashboardOrganizationIdGeneratorsRouteRouteChildren =
  {
    DashboardOrganizationIdGeneratorsGeneratorIdRouteRoute:
      DashboardOrganizationIdGeneratorsGeneratorIdRouteRouteWithChildren
  }

const DashboardOrganizationIdGeneratorsRouteRouteWithChildren =
  DashboardOrganizationIdGeneratorsRouteRoute._addFileChildren(
    DashboardOrganizationIdGeneratorsRouteRouteChildren
  )

interface DashboardOrganizationIdRouteRouteChildren {
  DashboardOrganizationIdGeneratorsRouteRoute: typeof DashboardOrganizationIdGeneratorsRouteRouteWithChildren
  DashboardOrganizationIdIndexRoute: typeof DashboardOrganizationIdIndexRoute
  DashboardOrganizationIdSettingsIndexRoute: typeof DashboardOrganizationIdSettingsIndexRoute
}

const DashboardOrganizationIdRouteRouteChildren: DashboardOrganizationIdRouteRouteChildren =
  {
    DashboardOrganizationIdGeneratorsRouteRoute:
      DashboardOrganizationIdGeneratorsRouteRouteWithChildren,
    DashboardOrganizationIdIndexRoute: DashboardOrganizationIdIndexRoute,
    DashboardOrganizationIdSettingsIndexRoute:
      DashboardOrganizationIdSettingsIndexRoute
  }

const DashboardOrganizationIdRouteRouteWithChildren =
  DashboardOrganizationIdRouteRoute._addFileChildren(
    DashboardOrganizationIdRouteRouteChildren
  )

interface DashboardRouteRouteChildren {
  DashboardOrganizationIdRouteRoute: typeof DashboardOrganizationIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationIdRouteRoute:
    DashboardOrganizationIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
